module.exports = {
  overrides: [
    {
      files: ['*.json'],
      extends: ['plugin:jsonc/recommended-with-json'],
    },
    {
      files: ['*.jsonc'],
      extends: ['plugin:jsonc/recommended-with-jsonc'],
    },
    {
      files: ['*.json5'],
      extends: ['plugin:jsonc/recommended-with-json5'],
    },
    {
      files: ['*.json', '*.jsonc', '*.json5'],
      extends: ['plugin:jsonc/prettier'],
      parser: 'jsonc-eslint-parser',
    },
    {
      files: ['package.json'],
      rules: {
        'jsonc/sort-keys': [
          'error',
          {
            pathPattern: '^$',
            order: [
              'name',
              'version',
              'private',
              'publishConfig',
              'description',
              'keywords',
              'homepage',
              'repository',
              'bugs',
              'license',
              'funding',
              'author',
              'contributors',
              'files',
              'type',
              'main',
              'module',
              'browser',
              'bin',
              'man',
              'directories',
              'exports',
              'imports',
              'scripts',
              'config',
              'dependencies',
              'devDependencies',
              'peerDependencies',
              'peerDependenciesMeta',
              'bundledDependencies',
              'optionalDependencies',
              'overrides',
              'packageManager',
              'engines',
              'os',
              'cpu',
              'workspaces',
            ],
          },
          {
            pathPattern: '^(?:dev|peer|optional|bundled)?[Dd]ependencies$',
            order: { type: 'asc' },
          },
        ],
      },
    },
  ],
};
